[package]
name = "convert_ages_to_days_smorci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[[bin]]
name = "convert_ages_to_days_smorci"
test = true

[dependencies]
num-bigint = "0.4.4"
