[package]
name = "convert_ages_to_days_brainrake_example_web"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_ages_to_days_brainrake = { path = "../.." }
web-sys = "0.3"
yew = { version = "0.21", features = ["csr"] }
